language: python
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
    - libxcb-randr0-dev
    - libxcb-xtest0-dev
    - libxcb-xinerama0-dev
    - libxcb-shape0-dev
    - libxcb-xkb-dev
    - libxcb-render-util0
    - libxcb-icccm4
    - libxcb-keysyms1
    - libxcb-image0
dist: xenial
services:
  - xvfb

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# command to run tests
script:
  - pytest
