language: python
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
dist: xenial
services:
  - xvfb

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# command to run tests
script:
  - pytest
